# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/autofs/unitytravail/travail/sazarfane/Projet techno/lightup-a42c"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/autofs/unitytravail/travail/sazarfane/Projet techno/lightup-a42c"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/autofs/unitytravail/travail/sazarfane/Projet techno/lightup-a42c/CMakeFiles" "/autofs/unitytravail/travail/sazarfane/Projet techno/lightup-a42c//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/autofs/unitytravail/travail/sazarfane/Projet techno/lightup-a42c/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named game_text

# Build rule for target.
game_text: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 game_text
.PHONY : game_text

# fast build rule for target.
game_text/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_text.dir/build.make CMakeFiles/game_text.dir/build
.PHONY : game_text/fast

#=============================================================================
# Target rules for targets named libgame

# Build rule for target.
libgame: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libgame
.PHONY : libgame

# fast build rule for target.
libgame/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libgame.dir/build.make CMakeFiles/libgame.dir/build
.PHONY : libgame/fast

game_aux.o: game_aux.c.o

.PHONY : game_aux.o

# target to build an object file
game_aux.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libgame.dir/build.make CMakeFiles/libgame.dir/game_aux.c.o
.PHONY : game_aux.c.o

game_aux.i: game_aux.c.i

.PHONY : game_aux.i

# target to preprocess a source file
game_aux.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libgame.dir/build.make CMakeFiles/libgame.dir/game_aux.c.i
.PHONY : game_aux.c.i

game_aux.s: game_aux.c.s

.PHONY : game_aux.s

# target to generate assembly for a file
game_aux.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libgame.dir/build.make CMakeFiles/libgame.dir/game_aux.c.s
.PHONY : game_aux.c.s

game_text.o: game_text.c.o

.PHONY : game_text.o

# target to build an object file
game_text.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_text.dir/build.make CMakeFiles/game_text.dir/game_text.c.o
.PHONY : game_text.c.o

game_text.i: game_text.c.i

.PHONY : game_text.i

# target to preprocess a source file
game_text.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_text.dir/build.make CMakeFiles/game_text.dir/game_text.c.i
.PHONY : game_text.c.i

game_text.s: game_text.c.s

.PHONY : game_text.s

# target to generate assembly for a file
game_text.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_text.dir/build.make CMakeFiles/game_text.dir/game_text.c.s
.PHONY : game_text.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... game_text"
	@echo "... libgame"
	@echo "... game_aux.o"
	@echo "... game_aux.i"
	@echo "... game_aux.s"
	@echo "... game_text.o"
	@echo "... game_text.i"
	@echo "... game_text.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

